version: 1


worlds:
  # whitelist / blacklist
  mode: whitelist
  list:
    - world


# MiniMessage 형식: https://webui.advntr.dev/
#
# 특정 메시지에서는 다음 포맷을 지원합니다.
#
# "<bossbar:color:time>이것은 보스바 메시지입니다.</bossbar>"
# "<actionbar:time>이것은 액션바 메시지입니다.</actionbar>"
# "<title:fadeIn:stay:fadeOut>이것은 메인 타이틀 메시지입니다.</title><subtitle>서브 타이틀 메시지입니다.</subtitle>"
#
# time의 단위는 기본적으로 tick입니다, 20틱 = 1초
#
# {} 안에 원하는 옵션을 작성해주세요.
# timer [필수] ex) {timer=0h30m}
# sound [선택] ex) {timer=0h30m,sound=entity.experience_orb.pickup}
#
# 작성 방식 : 메시지{옵션}
#
scheduler:
  #
  # 1h(시간) , 2m(분) , 3s(초)
  #
  timer: "0h 30m 0s"
  # 청소 메시지 -> 옵션 미지원
  clear: "바닥에 떨어진 아이템 %del% 개가 사라졌습니다."
  messages:
    - "5초뒤 바닥청소가 진행됩니다. 조심하세요!{timer=0h29m55s,sound=entity.experience_orb.pickup}"
    - "4초뒤 바닥청소가 진행됩니다. 조심하세요!{timer=0h29m56s,sound=entity.experience_orb.pickup}"
    - "3초뒤 바닥청소가 진행됩니다. 조심하세요!{timer=0h29m57s,sound=entity.experience_orb.pickup}"
    - "2초뒤 바닥청소가 진행됩니다. 조심하세요!{timer=0h29m58s,sound=entity.experience_orb.pickup}"
    - "1초뒤 바닥청소가 진행됩니다. 조심하세요!{timer=0h29m59s,sound=entity.experience_orb.pickup}"




